# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

from __future__ import annotations

from typing import Any, TypeVar

from PyQt6 import QtCore

T = TypeVar("T")


class CancellableBaseWorker(QtCore.QObject):  # type: ignore[misc]
    batch_completed = QtCore.pyqtSignal(float, object, name="batchCompleted")
    finished = QtCore.pyqtSignal(name="finished")
    failed = QtCore.pyqtSignal(Exception, name="failed")

    def __init__(self, do_batches_require_ack: bool):
        super().__init__()

        self.cancellation_requested = False
        self.cancellation_flag_mutex = QtCore.QReadWriteLock()
        self.batch_ack_mutex: QtCore.QMutex | None = QtCore.QMutex() if do_batches_require_ack else None
        self.wait_on_batch_processed_acknowledgement_condition: QtCore.QWaitCondition | None = (
            QtCore.QWaitCondition() if do_batches_require_ack else None
        )

    # TODO: Is this comment still required if we manually invoke the function instead of using signals? Check AI bots?
    # In the cross thread communication between the main thread (rendering the GUI) and the worker thread we had the issue that if we define the slot function with a QtCore.pyqtSlot() decorator
    # the main thread will not invoke said slot in the worker thread but we do not know exactly we since other signal->slot connections between the two threads function when being defined with
    # corresponding decorators. Thus for now we define the slot without a decorator.
    #
    # One explanation, generated by an AI agent, was:
    # The decisive moment is when the decorator runs, not when you later do moveToThread.
    # At import time (define time) the worker instance already exists and lives in the GUI thread; the decorator therefore registers the slot in the GUI thread's meta-object.
    # Afterwards you move the object to the worker thread, but the meta-object data that Qt uses to locate the slot stays where it was created - in the GUI thread.
    # When the GUI thread later emits the signal, Qt again looks in the GUI thread's meta-object, finds the entry that was created by the decorator, and tries to invoke it.
    # Because the slot entry is marked as "belonging to another thread" (the worker thread), Qt posts a queued meta-call to that thread … but the worker thread has no corresponding meta-object entry, so nothing is executed.
    # If you remove the decorator the connection is handled purely in Python (Qt simply stores the callable); the queued connection then works, because Python callables are independent of the meta-object system.
    # In short:
    #    - pyqtSlot must be executed after the object has been moved to the target thread, or
    #    - drop the decorator and rely on the automatic queued connection that PyQt already provides.
    def request_cancellation(self) -> None:
        self.set_cancellation_requested_flag(True)
        self.ack_batch_processed()

    # Again we define the slot without the corresponding decorator, for further information we refer to the request_cancellation function.
    def ack_batch_processed(self) -> None:
        if self.batch_ack_mutex is not None and self.wait_on_batch_processed_acknowledgement_condition is not None:
            with QtCore.QMutexLocker(self.batch_ack_mutex):
                self.wait_on_batch_processed_acknowledgement_condition.wakeOne()

    def is_cancellation_requested(self) -> bool:
        cancellation_requested: bool = False
        self.cancellation_flag_mutex.lockForRead()
        cancellation_requested = self.cancellation_requested
        self.cancellation_flag_mutex.unlock()
        return cancellation_requested

    def set_cancellation_requested_flag(self, flag_value: bool) -> None:
        self.cancellation_flag_mutex.lockForWrite()
        self.cancellation_requested = flag_value
        self.cancellation_flag_mutex.unlock()

    @staticmethod
    def are_list_of_batch_items_of_type(batch_data: Any, expected_batch_element_type: type[T]) -> bool:
        return isinstance(batch_data, list) and all(
            isinstance(batch_item, expected_batch_element_type) for batch_item in batch_data
        )
